// zh.js
export const zh = {
    home: "首页",
    features: "功能",
    community: "社区",
    download: "下载",
    playNow: "立即播放",
    dynamicMusicExperience: "动态音乐体验",
    uniqueCharacters: "独特角色",
    creativeVisuals: "创意视觉效果",
    customizableLevels: "可自定义关卡",
    howToPlay: "如何玩 Sprunki 游戏？",
    startYourMusicalJourney: "开始你的音乐之旅",
    creativeTechniques: "创意技巧",
    exploreMorePossibilities: "探索更多可能性",
    frequentlyAskedQuestions: "常见问题",
    whatCharactersAreAvailable: "游戏中有哪些角色？",
    howToCreateMusicBeats: "如何创建音乐节拍？",
    isThereATimeLimit: "游戏有时间限制吗？",
    howToUnlockNewContent: "如何解锁新内容？",
    canIPlayOnMobile: "我可以在移动设备上玩吗？",
    howToImproveScore: "如何提高我的分数？",
    areTherePowerUps: "游戏中有增强道具吗？",
    howToCompeteWithFriends: "如何与朋友竞争？",
    doesSprunkiHaveAchievements: "Sprunki 有成就系统吗？",
    doesSprunkiReceiveUpdates: "Sprunki 会定期更新内容吗？",
  };